FROM node:22-slim

WORKDIR /app

COPY package*.json ./

RUN npm install --legacy-peer-deps

COPY . .

EXPOSE 4200

# Assuming Angular CLI is run via npm start
CMD ["npm", "start", "--", "--host", "0.0.0.0"]
